export const config = {
  lightTheme: "light",
  darkTheme: "dark",
  themes: [
    ["light", "light"],
    ["cupcake", "light"],
    ["bumblebee", "light"],
    ["emerald", "light"],
    ["corporate", "light"],
    ["retro", "light"],
    ["cyberpunk", "light"],
    ["valentine", "light"],
    ["garden", "light"],
    ["aqua", "light"],
    ["lofi", "light"],
    ["pastel", "light"],
    ["fantasy", "light"],
    ["wireframe", "light"],
    ["cmyk", "light"],
    ["autumn", "light"],
    ["acid", "light"],
    ["lemonade", "light"],
    ["winter", "light"],
    ["dark", "dark"],
    ["synthwave", "dark"],
    ["halloween", "dark"],
    ["forest", "dark"],
    ["black", "dark"],
    ["luxury", "dark"],
    ["dracula", "dark"],
    ["business", "dark"],
    ["night", "dark"],
    ["coffee", "dark"],
  ],
}
